# Generated by Django 2.2.7 on 2019-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_type', models.CharField(blank=True, max_length=50)),
                ('simbol', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('control_type', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(default='_', unique=True)),
            ],
        ),
    ]
