# Generated by Django 2.2.7 on 2019-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_aid_kit', '0002_drugmaker_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default='_', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default='_', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='drugmaker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='active_substances',
            field=models.ManyToManyField(related_name='medicament', to='my_first_aid_kit.ActiveSubstances'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='pharma_group',
            field=models.ManyToManyField(related_name='medicament', to='my_first_aid_kit.PharmaGroup'),
        ),
    ]
