# Generated by Django 2.2.7 on 2019-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='p_library/books/covers/%Y/%m/%d'),
        ),
    ]
