# Generated by Django 2.2.7 on 2019-11-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
