# Generated by Django 2.2.7 on 2019-11-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20191117_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='author', to='p_library.Tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='book', to='p_library.Tag'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='publisher', to='p_library.Tag'),
        ),
    ]
