# Generated by Django 2.2.7 on 2019-11-13 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20191112_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookscopy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
