# Generated by Django 2.2.7 on 2019-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_bookscopy_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='library_card',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
