# Generated by Django 2.2.7 on 2019-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20191113_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
