# Generated by Django 2.2.7 on 2019-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20191113_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='p_library.Tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='p_library.Tag'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='p_library.Tag'),
        ),
    ]
